name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types:  #[opened, synchronize]
      - opened
      - synchronize
    branches:
      - main
      #- 'releases/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opened or synchronized AND base branch is main"


#  node-20-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#      - run: npm ci
#      - run: npm run test